version: "3"

services:
  api:
    build: ./api
    command: npm run dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - APP_PORT=3001
      - APP_HOST=http://127.0.0.1
      - MONGO_DB_URL=mongodb://api_db:27017/api
    volumes:
      - ./api/src:/app/src
    depends_on:
      - api_db

  api_db:
    image: mongo:7
    volumes:
      - api_mongo_db:/data/db

  frontend:
    build: ./front
    command: npm run dev
    restart: unless-stopped
    ports:
      - "3000:5173"
    volumes:
      - "./front:/app"

volumes:
  api_mongo_db:
